"""
orchestrator.py - The Level 4 Super-Agent "Brain"
------------------------------------------------
Role: Acts as the CPU/Brain in the Agent Infrastructure.
Logic: Manages the sequence of Skills, executes Tools, and performs 
       autonomous decision-making (Retry & Refine) based on metrics.
"""

import os
import json
import subprocess
import time

class Level4Orchestrator:
    def __init__(self):
        self.project_root = os.getcwd()
        self.agent_folder = os.path.join(self.project_root, "Agent_Folder")
        self.skills_path = os.path.join(".claude", "skills")
        self.session_history = []
        self.threshold = 0.85

    def log_step(self, role, message):
        """Manages the Memory (Context Window) of the chain."""
        self.session_history.append({"role": role, "content": message, "timestamp": time.time()})

    def get_skill_instruction(self, skill_name):
        """Reads the 'Expert Persona' from the Skill.md file."""
        path = os.path.join(self.skills_path, skill_name, "Skill.md")
        if os.path.exists(path):
            with open(path, 'r', encoding='utf-8') as f:
                return f.read()
        return "You are a helpful translation assistant."

    def call_agent(self, skill_name, input_text, critique=None):
        """
        Simulates the execution of a Skill. 
        In a production Level 4 system, this would be an API call to the LLM 
        passing the Skill.md as the System Prompt.
        """
        persona = self.get_skill_instruction(skill_name)
        
        print(f"--- [ACTING] {skill_name} is processing... ---")
        
        # INSTRUCTION: In a real implementation, the Orchestrator sends 
        # (persona + input_text + critique) to the LLM.
        # For this script, we simulate the 'Reasoning' step.
        
        self.log_step(skill_name, f"Input: {input_text} | Critique: {critique}")
        
        # Placeholder for actual LLM call
        # return llm.generate(system=persona, prompt=input_text)
        return f"[Simulated Translation of '{input_text[:20]}...' via {skill_name}]"

    def run_eval_tool(self, original, final):
        """Executes the 'Hands' (eval_drift.py) to get empirical data."""
        try:
            # We use subprocess to run our Python evaluation tool
            cmd = ["python", "eval_drift.py", original, final]
            result = subprocess.run(cmd, capture_output=True, text=True)
            if result.returncode != 0:
                print(f"⚠️ Tool Error: {result.stderr}")
                return {"drift_score": 0.5, "error": result.stderr}
            return json.loads(result.stdout)
        except Exception as e:
            print(f"⚠️ Execution Exception: {str(e)}")
            return {"drift_score": 0.5, "error": str(e)}

    def execute_chain(self, original_text):
        print(f"🚀 MISSION START: '{original_text}'")
        self.log_step("User", original_text)

        attempts = 0
        max_attempts = 3
        current_en = original_text
        
        while attempts < max_attempts:
            attempts += 1
            print(f"\n🔄 --- CHAIN ATTEMPT {attempts} ---")

            # 1. EN -> FR
            fr_text = self.call_agent("English-French-Expert", current_en)

            # 2. FR -> HE
            he_text = self.call_agent("French-Hebrew-Expert", fr_text)

            # 3. HE -> EN
            final_en = self.call_agent("Hebrew-English-Expert", he_text)

            # 4. EVALUATE
            metrics = self.run_eval_tool(original_text, final_en)
            score = metrics.get("drift_score", 0)

            print(f"📊 Current Drift Score: {score}")

            if score >= self.threshold:
                print("✅ MISSION SUCCESS: Semantic Integrity Preserved.")
                self.generate_report(original_text, final_en, metrics, attempts)
                return final_en
            else:
                print(f"⚠️ DRIFT DETECTED ({score}). Initiating Critique & Refine Loop...")
                # Level 4 Logic: The Orchestrator generates a critique for the agents
                critique = f"The drift score is too low. Ensure you preserve the 'Semantic Cloud' of '{original_text}'."
                # On the next loop, the agents receive the critique.
        
        print("❌ MISSION FAILED: Max attempts reached without satisfying metrics.")
        self.generate_report(original_text, final_en, metrics, attempts)
        return final_en

    def generate_report(self, original, final, metrics, attempts):
        report_path = os.path.join(self.agent_folder, "FINAL_REPORT.md")
        content = f"""# Broken Telephone: Final Mission Report
Generated by: Level 4 Orchestrator
Status: {metrics.get('status', 'Unknown')}

## Results
- **Original English:** {original}
- **Final English:** {final}
- **Total Chain Attempts:** {attempts}

## Metrics
- **Final Drift Score:** {metrics.get('drift_score')}
- **Vector Distance Logic:** {metrics.get('status')}

## Reasoning Trace
The Orchestrator successfully managed {attempts} hops through the semantic forest. 
The final output is deemed acceptable according to the Lesson 5 Guardrails.
"""
        with open(report_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"📝 Report generated at: {report_path}")

if __name__ == "__main__":
    orchestrator = Level4Orchestrator()
    # Test execution
    orchestrator.execute_chain("Don't count your chickens before they've hatched.")
